### ISSUE TITLE
Ordering Decendants

### ISSUE THREAD

**Issue by MatthewAry** [overlookmotel/sequelize-hierarchy#134]
I saw this: #32 
Either I'm doing something wrong, or this problem still exists.

My taxonomy table is my hierarchy. Each taxonomy entry is has a reference to a vocabulary ID. It allows me to manage and label multiple trees. I get the root nodes for a vocabulary and then get the tree off those nodes. I want to order the descendants of those nodes so after digging around your test suite and issue #32 I felt I might have the solution. Nope.

Weight is a numbered field. I'm trying to get the lightest nodes to be a the top of the list in its given hierarchy. Right now my only workaround to this problem is to process the result to correct the order.

Here's my code.

```
vocabulary.findById(vocabularyId, {
          include: [{
            model: taxonomy,
            as: 'taxonomies',
            where: {
              hierarchyLevel: 1
            },
            include: [{
              model: taxonomy,
              as: 'descendents',
              hierarchy: true,
              attributes: ['id', 'name', 'parentId', 'hierarchyLevel', 'weight']
            }],
            attributes: ['id', 'name', 'parentId', 'hierarchyLevel', 'weight'],
            order: [[{modal: taxonomy}, {modal: taxonomy, as: 'descendents'}, 'weight', 'ASC']]
          }],
          attributes: ['id', 'name']
        })
```

For me returns the following:

```
  {
    "id": 1,
    "name": "FAQ Categories",
    "taxonomies": [
      {
        "id": 1,
        "name": "General",
        "parentId": null,
        "hierarchyLevel": 1,
        "weight": 0,
        "children": [
          {
            "id": 3,
            "name": "Projects",
            "parentId": 1,
            "hierarchyLevel": 2,
            "weight": 1,
            "children": [
              {
                "id": 2,
                "name": "Filters",
                "parentId": 3,
                "hierarchyLevel": 3,
                "weight": 1
              }
            ]
          },
          {
            "id": 5,
            "name": "Workbook Access Control",
            "parentId": 1,
            "hierarchyLevel": 2,
            "weight": 0
          }
        ]
      },
      {
        "id": 4,
        "name": "Administration",
        "parentId": null,
        "hierarchyLevel": 1,
        "weight": 1,
        "children": []
      }
    ]
  }
]
```

I'm expecting workbook access control to be above projects. 
Here's what I'm using:
```
    "sequelize": "^4.2.0",
    "sequelize-hierarchy": "^1.3.1",
```

Thanks for your help!

**Comment by overlookmotel** [comment]
Hi.

`order` directives only work at base level of a query (i.e. not inside an `include`). So I think your `order: [[{model: taxonomy} ...` line should be last line after final `attributes: ['id', 'name']`.

Please let me know if that works.

**Comment by MatthewAry** [comment]
I tried what you said and got an error that the weight attribute or field is ambiguous in my order statement.

Here's the altered code. Note that it has changed a little since I filed my issue.
```
vocabulary.findById(vocabularyId, {
  include: [{
    model: taxonomy,
    as: 'taxonomies',
    where: {
      hierarchyLevel: 1
    },
    include: [{
      model: taxonomy,
      as: 'descendents',
      hierarchy: true,
      attributes: ['id', 'name', 'parentId', 'hierarchyLevel', 'weight']
    }],
    attributes: ['id', 'name', 'parentId', 'hierarchyLevel', 'weight']
  }],
  attributes: ['id', 'name'],
  order: ['name', [{modal: taxonomy}, {modal: taxonomy, as: 'descendents'}, 'weight', 'ASC']]
}
```

And here is my error.

```
{ SequelizeDatabaseError: Column 'weight' in order clause is ambiguous
    at Query.formatError (node_modules/sequelize/lib/dialects/mysql/query.js:222:16)
    at Query.connection.query [as onResult] (node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (node_modules/mysql2/lib/commands/command.js:31:12)
    at Connection.handlePacket (node_modules/mysql2/lib/connection.js:417:28)
    at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:93:16)
    at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:73:14)
    at Socket.<anonymous> (node_modules/mysql2/lib/connection.js:101:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.EventEmitter.emit (node_modules/sc-domain/index.js:12:31)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
  name: 'SequelizeDatabaseError',
  parent: 
   { Error: Column 'weight' in order clause is ambiguous
       at Packet.asError (node_modules/mysql2/lib/packets/packet.js:667:13)
       at Query.Command.execute (node_modules/mysql2/lib/commands/command.js:29:22)
       at Connection.handlePacket (node_modules/mysql2/lib/connection.js:417:28)
       at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:93:16)
       at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:73:14)
       at Socket.<anonymous> (node_modules/mysql2/lib/connection.js:101:29)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at Socket.EventEmitter.emit (node_modules/sc-domain/index.js:12:31)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:547:20)
     code: 'ER_NON_UNIQ_ERROR',
     errno: 1052,
     sqlState: '#23000',
     sql: 'SELECT `vocabulary`.`id`, `vocabulary`.`name`, `taxonomies`.`id` AS `taxonomies.id`, `taxonomies`.`name` AS `taxonomies.name`, `taxonomies`.`parentId` AS `taxonomies.parentId`, `taxonomies`.`hierarchyLevel` AS `taxonomies.hierarchyLevel`, `taxonomies`.`weight` AS `taxonomies.weight`, `taxonomies->descendents`.`id` AS `taxonomies.descendents.id`, `taxonomies->descendents`.`name` AS `taxonomies.descendents.name`, `taxonomies->descendents`.`parentId` AS `taxonomies.descendents.parentId`, `taxonomies->descendents`.`hierarchyLevel` AS `taxonomies.descendents.hierarchyLevel`, `taxonomies->descendents`.`weight` AS `taxonomies.descendents.weight`, `taxonomies->descendents->taxonomyancestor`.`taxonomyId` AS `taxonomies.descendents.taxonomyancestor.taxonomyId`, `taxonomies->descendents->taxonomyancestor`.`ancestorId` AS `taxonomies.descendents.taxonomyancestor.ancestorId` FROM `app_Vocabularies` AS `vocabulary` INNER JOIN `app_Taxonomies` AS `taxonomies` ON `vocabulary`.`id` = `taxonomies`.`vocabularyId` AND `taxonomies`.`hierarchyLevel` = 1 LEFT OUTER JOIN ( `app_TaxonomyAncestors` AS `taxonomies->descendents->taxonomyancestor` INNER JOIN `app_Taxonomies` AS `taxonomies->descendents` ON `taxonomies->descendents`.`id` = `taxonomies->descendents->taxonomyancestor`.`taxonomyId`) ON `taxonomies`.`id` = `taxonomies->descendents->taxonomyancestor`.`ancestorId` WHERE `vocabulary`.`id` = 1 ORDER BY `vocabulary`.`name`, ``.`weight` ASC;' },
  original: 
   { Error: Column 'weight' in order clause is ambiguous
       at Packet.asError (node_modules/mysql2/lib/packets/packet.js:667:13)
       at Query.Command.execute (node_modules/mysql2/lib/commands/command.js:29:22)
       at Connection.handlePacket (node_modules/mysql2/lib/connection.js:417:28)
       at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:93:16)
       at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:73:14)
       at Socket.<anonymous> (node_modules/mysql2/lib/connection.js:101:29)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at Socket.EventEmitter.emit (node_modules/sc-domain/index.js:12:31)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:547:20)
     code: 'ER_NON_UNIQ_ERROR',
     errno: 1052,
     sqlState: '#23000',
     sql: 'SELECT `vocabulary`.`id`, `vocabulary`.`name`, `taxonomies`.`id` AS `taxonomies.id`, `taxonomies`.`name` AS `taxonomies.name`, `taxonomies`.`parentId` AS `taxonomies.parentId`, `taxonomies`.`hierarchyLevel` AS `taxonomies.hierarchyLevel`, `taxonomies`.`weight` AS `taxonomies.weight`, `taxonomies->descendents`.`id` AS `taxonomies.descendents.id`, `taxonomies->descendents`.`name` AS `taxonomies.descendents.name`, `taxonomies->descendents`.`parentId` AS `taxonomies.descendents.parentId`, `taxonomies->descendents`.`hierarchyLevel` AS `taxonomies.descendents.hierarchyLevel`, `taxonomies->descendents`.`weight` AS `taxonomies.descendents.weight`, `taxonomies->descendents->taxonomyancestor`.`taxonomyId` AS `taxonomies.descendents.taxonomyancestor.taxonomyId`, `taxonomies->descendents->taxonomyancestor`.`ancestorId` AS `taxonomies.descendents.taxonomyancestor.ancestorId` FROM `app_Vocabularies` AS `vocabulary` INNER JOIN `app_Taxonomies` AS `taxonomies` ON `vocabulary`.`id` = `taxonomies`.`vocabularyId` AND `taxonomies`.`hierarchyLevel` = 1 LEFT OUTER JOIN ( `app_TaxonomyAncestors` AS `taxonomies->descendents->taxonomyancestor` INNER JOIN `app_Taxonomies` AS `taxonomies->descendents` ON `taxonomies->descendents`.`id` = `taxonomies->descendents->taxonomyancestor`.`taxonomyId`) ON `taxonomies`.`id` = `taxonomies->descendents->taxonomyancestor`.`ancestorId` WHERE `vocabulary`.`id` = 1 ORDER BY `vocabulary`.`name`, ``.`weight` ASC;' },
  sql: 'SELECT `vocabulary`.`id`, `vocabulary`.`name`, `taxonomies`.`id` AS `taxonomies.id`, `taxonomies`.`name` AS `taxonomies.name`, `taxonomies`.`parentId` AS `taxonomies.parentId`, `taxonomies`.`hierarchyLevel` AS `taxonomies.hierarchyLevel`, `taxonomies`.`weight` AS `taxonomies.weight`, `taxonomies->descendents`.`id` AS `taxonomies.descendents.id`, `taxonomies->descendents`.`name` AS `taxonomies.descendents.name`, `taxonomies->descendents`.`parentId` AS `taxonomies.descendents.parentId`, `taxonomies->descendents`.`hierarchyLevel` AS `taxonomies.descendents.hierarchyLevel`, `taxonomies->descendents`.`weight` AS `taxonomies.descendents.weight`, `taxonomies->descendents->taxonomyancestor`.`taxonomyId` AS `taxonomies.descendents.taxonomyancestor.taxonomyId`, `taxonomies->descendents->taxonomyancestor`.`ancestorId` AS `taxonomies.descendents.taxonomyancestor.ancestorId` FROM `app_Vocabularies` AS `vocabulary` INNER JOIN `app_Taxonomies` AS `taxonomies` ON `vocabulary`.`id` = `taxonomies`.`vocabularyId` AND `taxonomies`.`hierarchyLevel` = 1 LEFT OUTER JOIN ( `app_TaxonomyAncestors` AS `taxonomies->descendents->taxonomyancestor` INNER JOIN `app_Taxonomies` AS `taxonomies->descendents` ON `taxonomies->descendents`.`id` = `taxonomies->descendents->taxonomyancestor`.`taxonomyId`) ON `taxonomies`.`id` = `taxonomies->descendents->taxonomyancestor`.`ancestorId` WHERE `vocabulary`.`id` = 1 ORDER BY `vocabulary`.`name`, ``.`weight` ASC;' }
TypeError: Cannot read property 'taxonomies' of null
    at _.each.vocabulary (repositories/ContentRepository.js:667:61)
    at arrayEach (node_modules/lodash/lodash.js:537:11)
    at Function.forEach (node_modules/lodash/lodash.js:9359:14)
    at db.Sequelize.Promise.all.then.vocabularies (repositories/ContentRepository.js:666:13)
    at tryCatcher (node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (node_modules/sequelize/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (node_modules/sequelize/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Unhandled rejection InvalidActionError: Response 21 has already been sent
    at Response._respond (node_modules/socketcluster-server/response.js:12:11)
    at Response.error (node_modules/socketcluster-server/response.js:43:10)
    at Response.callback (node_modules/socketcluster-server/response.js:49:10)
    at db.vocabularyNodeType.findAll.then.catch.err (repositories/ContentRepository.js:674:7)
    at tryCatcher (node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

Here are the define statements for the used tables.

```
module.exports = function (sequelize, DataTypes) {
  const Vocabulary = sequelize.define('vocabulary', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    description: {
      type: DataTypes.TEXT
    },
    protected: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    }
  }, {
    tableName: 'app_Vocabularies'
  })
  Vocabulary.associate = (models) => {
    Vocabulary.hasMany(models.taxonomy, {as: 'taxonomies'})
  }

  return Vocabulary
}
```
```
module.exports = function (sequelize, DataTypes) {
  const Taxonomy = sequelize.define('taxonomy', {
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    description: {
      type: DataTypes.TEXT('long')
    },
    weight: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    protected: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    }
  }, {
    tableName: 'app_Taxonomies',
    hierarchy: {
      throughTable: 'app_TaxonomyAncestors',
      onDelete: 'CASCADE'
    }
  })

  Taxonomy.associate = (models) => {
    Taxonomy.belongsTo(models.vocabulary)
  }
  return Taxonomy
}
```
If you have any more suggestions I would be happy to try them out.

Thanks!

**Comment by overlookmotel** [comment]
I think you have a couple of problems with your `order` clause. Firstly, a misspelling (`model` not `modal`) and also misuse of the grammar. Try this:

`order: [['name'], [{model: taxonomy, as: 'taxonomies'}, {model: taxonomy, as: 'descendents'}, 'weight', 'ASC']]`

**Comment by overlookmotel** [comment]
If that still doesn't work, use `logging: console.log` in query options to get output of the SQL it's creating.

**Comment by MatthewAry** [comment]
Good grief. Hahahaha, that misspelling. So I was doing something wrong. Makes sense. The output looks correct now.

```
{
  "id": 1,
  "name": "FAQ Categories",
  "taxonomies": [
    {
      "id": 1,
      "name": "General",
      "parentId": null,
      "hierarchyLevel": 1,
      "weight": 0,
      "children": [
        {
          "id": 6,
          "name": "Forgettable 1",
          "parentId": 1,
          "hierarchyLevel": 2,
          "weight": 0
        },
        {
          "id": 3,
          "name": "Projects",
          "parentId": 1,
          "hierarchyLevel": 2,
          "weight": 1,
          "children": [
            {
              "id": 2,
              "name": "Filters",
              "parentId": 3,
              "hierarchyLevel": 3,
              "weight": 1
            }
          ]
        }
      ]
    },
    {
      "id": 4,
      "name": "Administration",
      "parentId": null,
      "hierarchyLevel": 1,
      "weight": 3,
      "children": [
        {
          "id": 5,
          "name": "Workbook Access Control",
          "parentId": 4,
          "hierarchyLevel": 2,
          "weight": 0
        },
        {
          "id": 7,
          "name": "Forgettable 2",
          "parentId": 4,
          "hierarchyLevel": 2,
          "weight": 1
        }
      ]
    }
  ]
}
```

Thanks for your help. Now I can rip out the recursive code that I wrote to order the returned result.

**Comment by overlookmotel** [comment]
Glad it's solved!
