### ISSUE TITLE
Problem with associations belongsToMany

### ISSUE THREAD

**Issue by Gazfay** [overlookmotel/sequelize-hierarchy#139]
Have some problems with associations belongsToMany. 
Case 1: 
1.Skill - hierarchy model
```
var Skill = sequelize.define('Skill', {
    name: DataTypes.STRING,
    type: DataTypes.INTEGER
  }, {
    hierarchy: {onDelete: 'CASCADE'},
    classMethods: {
      associate: function(models) {
        Skill.belongsToMany(models.People, { through: 'PeopleSkills', onDelete: 'CASCADE'});
      }
    }
  });
```
2. People model.
```
var People = sequelize.define('People', {
    firstName: DataTypes.STRING,
    lastName: DataTypes.STRING,
    imageId: {
      type: DataTypes.INTEGER,
      validate: {
        isInt: true
      }
    }
  }, {
    classMethods: {
      associate: function(models) {
        People.belongsTo(models.Image, {foreignKey: 'imageId', as: 'photo'}); 
        People.belongsToMany(models.Skill, {through: 'PeopleSkills', onDelete: 'CASCADE'});
      }
    }
  });
```
Many to many works fine!

Case 2:
1. Skill hierarchy model.
```
var Skill = sequelize.define('Skill', {
    name: DataTypes.STRING,
    type: DataTypes.INTEGER
  }, {
    hierarchy: {onDelete: 'CASCADE'},
    classMethods: {
      associate: function(models) {
        Skill.belongsToMany(models.People, { through: 'PeopleSkills', onDelete: 'CASCADE'});
        Skill.belongsToMany(models.Work, { through: 'WorksSkills', onDelete: 'CASCADE'});
      }
    }
  });
```
2. Work model.
```
var Work = sequelize.define('Work', {
    title: {
      allowNull: false,
      type: DataTypes.STRING
    },
    link: {
      allowNull: true,
      type: DataTypes.STRING
    }
  }, {
    classMethods: {
      associate: function(models) {
        Work.belongsTo(models.Image, {foreignKey: 'logoId', as: 'logo'}); 
        Work.belongsTo(models.Image, {foreignKey: 'workImageId', as: 'workImage'});
        Work.belongsToMany(models.Skill, { through: 'WorksSkills', onDelete: 'CASCADE'});
      }
    }
  });
```
This case throw error - 

```
D:\repositories\unicreo-rework\node_modules\sequelize\lib\associations\has-many.
js:34
    throw new Error('N:M associations are not supported with hasMany. Use belong
sToMany instead');
    ^

Error: N:M associations are not supported with hasMany. Use belongsToMany instea
d
    at new HasMany (D:\repositories\unicreo-rework\node_modules\sequelize\lib\as
sociations\has-many.js:34:11)
    at Model.Mixin.hasMany (D:\repositories\unicreo-rework\node_modules\sequeliz
e\lib\associations\mixin.js:186:21)
    at Model.isHierarchy (D:\repositories\unicreo-rework\node_modules\sequelize-
hierarchy\lib\modelExtends.js:86:9)
    at Sequelize.afterDefine (D:\repositories\unicreo-rework\node_modules\sequel
ize-hierarchy\lib\hooksUniversal.js:49:25)
    at D:\repositories\unicreo-rework\node_modules\sequelize\lib\hooks.js:127:21

    at Array.forEach (native)
    at Sequelize.runHooks (D:\repositories\unicreo-rework\node_modules\sequelize
\lib\hooks.js:125:13)
    at Sequelize.define (D:\repositories\unicreo-rework\node_modules\sequelize\l
ib\sequelize.js:635:8)
    at new BelongsToMany (D:\repositories\unicreo-rework\node_modules\sequelize\
lib\associations\belongs-to-many.js:161:43)
    at Model.Mixin.belongsToMany (D:\repositories\unicreo-rework\node_modules\se
quelize\lib\associations\mixin.js:265:21)
    at Model.associate (D:\repositories\unicreo-rework\models\skill.js:11:15)
    at D:\repositories\unicreo-rework\models\index.js:30:19
    at Array.forEach (native)
    at Object.<anonymous> (D:\repositories\unicreo-rework\models\index.js:27:17)

    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\repositories\unicreo-rework\app.js:16:16)
```
I can not understand what the problem is.
```
"sequelize": "^3.30.4",
"sequelize-hierarchy": "^1.3.1"
```

**Comment by overlookmotel** [comment]
@Gazfay Weird! Can you please try case 2 again without `hierarchy` option enabled. I suspect this may have nothing to do with sequelize-hierarchy and may be an issue with Sequelize itself.

**Comment by Gazfay** [comment]
Without hierarchy field it's works normally, no errors.

**Comment by Gazfay** [comment]
I fix it!

```
  var Skill = sequelize.define('Skill', {
    name: DataTypes.STRING,
    type: DataTypes.INTEGER
  }, {
    classMethods: {
      associate: function(models) {
        Skill.belongsToMany(models.People, { through: 'PeopleSkills', onDelete: 'CASCADE'});
        Skill.belongsToMany(models.Work, { through: 'WorksSkills', onDelete: 'CASCADE'});

      }
    }
  });
  Skill.isHierarchy({onDelete: 'CASCADE'})
  return Skill;
```
