### ISSUE TITLE
MS SQL support or not?

### ISSUE THREAD

**Issue by livemobile** [overlookmotel/sequelize-hierarchy#156]
MS SQL support or not?

**Comment by livemobile** [comment]
> sequelize-hierarchy@1.3.2 test C:\Users\Ujeen\Documents\GitLab\sequelize-hierarchy
> cross-env DIALECT=mssql npm run test-main


> sequelize-hierarchy@1.3.2 test-main C:\Users\Ujeen\Documents\GitLab\sequelize-hierarchy
> mocha --check-leaks --colors -t 30000 -R spec "test/**/*.test.js"

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules\sequelize\lib\sequelize.js:242:13
Sequelize version: 4.38.0
Dialect: mssql


  [MSSQL] Tests
    Hierarchy creation
      √ works via isHierarchy()
      √ works via define options
(sequelize) Warning: MSSQL does not support INTEGER with options. Plain `INTEGER` will be used instead., '
>> Check:', https://msdn.microsoft.com/en-us/library/ms187752%28v=sql.110%29.aspx
      √ works via defining in model attribute
      √ allows parentId and hierarchyLevel fields to already be defined
      options
        √ `through`
        √ `throughTable`
        √ `throughSchema`
    Methods
      #create
        for root level
          √ sets hierarchyLevel
          √ creates hierarchy table records
        for 2nd level
          √ sets hierarchyLevel
          √ creates hierarchy table records
        for 3rd level
          √ sets hierarchyLevel
          √ creates hierarchy table records
        throws
          √ if creating child of itself
      #updateAttributes
        for root level
          √ sets hierarchyLevel
          √ updates hierarchy table records
        for 2nd level
          √ sets hierarchyLevel
          √ updates hierarchy table records
        for 3rd level
          √ sets hierarchyLevel
          √ updates hierarchy table records
        descendents
          √ sets hierarchyLevel for descendents
          √ updates hierarchy table records for descendents
        throws
          √ if making item child of itself
          √ if making item child of one of its own descendents
      #destroy
        √ removes hierarchy table records
        1) throws error if try to destroy a record which has children
      #bulkCreate
        √ sets hierarchyLevel for all rows
        √ creates hierarchy table records for all rows
      #bulkUpdate
        √ sets hierarchyLevel for all rows
        √ creates hierarchy table records for all rows (46ms)
      #bulkDestroy
        √ removes hierarchy table records for all rows
        2) throws error if try to destroy a record which has children
      #find
        can retrieve
          √ children
          √ descendents
          √ parent
          √ ancestors
          √ other associations
        with hierarchy option
          √ findAll gets a structured tree
          √ find gets a structured tree
          √ find gets a structured tree when included from another model
          √ find gets a structured tree when included from another model 2 deep
          √ works with `raw` option
        works with scoped models
          √ with main model scoped
          √ with hierarchy model scoped
          √ with both models scoped
        handles empty result set with
          √ #find
          √ #findAll
          √ #find with an include
          √ #find with an empty include
          √ #find with empty descendents
      accessors
        can retrieve
          √ children
          √ descendents
          √ parent
          √ ancestors
        with hierarchy option
          √ getDescendents gets a structured tree
      setters
        legal
          √ setParent (47ms)
          √ addChild (63ms)
          createParent
            creates new item
              √ with correct parent
              √ with correct hierarchyLevel
              √ with correct hierarchy table entries
            sets current item
              √ to correct parent
              √ with correct hierarchyLevel
              √ with correct hierarchy table entries
          createChild
            √ with correct parent
            √ with correct hierarchyLevel
            √ with correct hierarchy table entries
        illegal methods not present
          √ setDescendents
          √ setAncestors
          √ addDescendent
          √ addAncestor
          √ addDescendents
          √ addAncestors
          √ createDescendent
          √ createAncestor
          √ removeDescendent
          √ removeAncestor
          √ removeDescendents
          √ removeAncestors
      #rebuildHierarchy
        √ recreates hierarchyLevel for all records
        √ recreates hierarchy table records
    Options
      underscored
        √ underscores field names and foreign keys
        √ does not override user supplied field names
      underscoredAll
        √ underscores through table name
        √ does not override user supplied `throughTable` option


  82 passing (21s)
  2 failing

  1) [MSSQL] Tests Methods #destroy throws error if try to destroy a record which has children:

      AssertionError: expected promise to be rejected with 'ForeignKeyConstraintError' but it was rejected with 'SequelizeDatabaseError: The DELETE statement conflicted with the SAME TABLE REFERENCE constraint "FK__folders__parentI__5540965B". The conflict occurred in database "testAVPrice", table "dbo.folders", column \'parentId\'.'
      + expected - actual

      -SequelizeDatabaseError: The DELETE statement conflicted with the SAME TABLE REFERENCE constraint
"FK__folders__parentI__5540965B". The conflict occurred in database "testAVPrice", table "dbo.folders",
column 'parentId'.
      +ForeignKeyConstraintError

      at getBasePromise.then.reason (node_modules\chai-as-promised\lib\chai-as-promised.js:206:30)
  From previous event:
      at Proxy.<anonymous> (node_modules\chai-as-promised\lib\chai-as-promised.js:169:53)
      at Proxy.<anonymous> (node_modules\chai-as-promised\lib\chai-as-promised.js:47:29)
      at Proxy.methodWrapper (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
      at Context.<anonymous> (test\all.test.js:393:34)

  2) [MSSQL] Tests Methods #bulkDestroy throws error if try to destroy a record which has children:

      AssertionError: expected promise to be rejected with 'ForeignKeyConstraintError' but it was rejected with 'SequelizeDatabaseError: The DELETE statement conflicted with the SAME TABLE REFERENCE constraint "FK__folders__parentI__1431ED0D". The conflict occurred in database "testAVPrice", table "dbo.folders", column \'parentId\'.'
      + expected - actual

      -SequelizeDatabaseError: The DELETE statement conflicted with the SAME TABLE REFERENCE constraint
"FK__folders__parentI__1431ED0D". The conflict occurred in database "testAVPrice", table "dbo.folders",
column 'parentId'.
      +ForeignKeyConstraintError

      at getBasePromise.then.reason (node_modules\chai-as-promised\lib\chai-as-promised.js:206:30)
  From previous event:
      at Proxy.<anonymous> (node_modules\chai-as-promised\lib\chai-as-promised.js:169:53)
      at Proxy.<anonymous> (node_modules\chai-as-promised\lib\chai-as-promised.js:47:29)
      at Proxy.methodWrapper (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
      at Context.<anonymous> (test\all.test.js:491:34)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! sequelize-hierarchy@1.3.2 test-main: `mocha --check-leaks --colors -t 30000 -R spec "test/**/*.test.js"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the sequelize-hierarchy@1.3.2 test-main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ujeen\AppData\Roaming\npm-cache\_logs\2018-08-11T12_56_41_888Z-debug.log
npm ERR! Test failed.  See above for more details.
PS C:\Users\Ujeen\Documents\GitLab\sequelize-hierarchy>

**Comment by livemobile** [comment]
I understand correctly that there are problems if try to destroy a record which has children?
