### ISSUE TITLE
Occasional failure on `bulkUpdate` test

### ISSUE THREAD

**Issue by overlookmotel** [overlookmotel/sequelize-hierarchy#162]
There's an occasional test failure, originally reported by @rusekr in https://github.com/overlookmotel/sequelize-hierarchy/pull/161#issuecomment-477929292

```
[MYSQL] Tests Methods #bulkUpdate "before each" hook for "sets hierarchyLevel for all rows":
SequelizeDatabaseError: Deadlock found when trying to get lock; try restarting transaction
```

I saw same error on Travis with MySQL on Sequelize v2. Re-ran the job and it passed. Unfortunately Travis log of the failure is lost. I guess will have to wait until it happens again.

**Comment by rusekr** [comment]
It's concurrency related so race condition bug. Two transactions on one column want to do update of it in one time and one of transactions fails because of locked row. I'm thinking thats old mysql code only handles cross locks that conflicted way (without something like transactions queues) because on postgre/sqlite there are no such conflicts. Only one thing is to do concurrent things in bulk update with one coloumn in one event at time (make some queue in builkupdate/ not all parallel or parallel only for unrelated columns) or handle exception and retry (which is not so good I think). I was googling that case and here the abstract answer: https://stackoverflow.com/a/2423921

**Comment by overlookmotel** [comment]
It happened again on Travis with MySQL and Sequelize 5.7.5 on Node 10.

Error:

```
SequelizeDatabaseError: Deadlock found when trying to get lock; try restarting transaction
      at Query.formatError (node_modules/sequelize/lib/dialects/mysql/query.js:241:16)
      at Query.handler [as onResult] (node_modules/sequelize/lib/dialects/mysql/query.js:48:23)
      at Query.execute (node_modules/mysql2/lib/commands/command.js:30:14)
      at Connection.handlePacket (node_modules/mysql2/lib/connection.js:449:32)
      at PacketParser.Connection.packetParser.p [as onPacket] (node_modules/mysql2/lib/connection.js:72:12)
      at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.Connection.stream.on.data (node_modules/mysql2/lib/connection.js:79:25)
      at addChunk (_stream_readable.js:284:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at Socket.Readable.push (_stream_readable.js:220:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  From previous event:
      at Query.run (node_modules/sequelize/lib/dialects/mysql/query.js:41:12)
      at Promise.try.then.connection (node_modules/sequelize/lib/sequelize.js:577:22)
  From previous event:
      at Promise.resolve.retryParameters (node_modules/sequelize/lib/sequelize.js:574:10)
      at /home/travis/build/overlookmotel/sequelize-hierarchy/node_modules/retry-as-promised/index.js:70:21
      at new Promise (<anonymous>)
      at retryAsPromised (node_modules/retry-as-promised/index.js:60:10)
      at Promise.try (node_modules/sequelize/lib/sequelize.js:554:30)
  From previous event:
      at Sequelize.query (node_modules/sequelize/lib/sequelize.js:511:23)
      at >=3.0.0 (lib/patches.js:46:54)
      at Promise.try.then.then.then (lib/hooksModel.js:287:12)
  From previous event:
      at Promise.try.then (lib/hooksModel.js:259:7)
  From previous event:
      at Function.beforeUpdate (lib/hooksModel.js:127:6)
      at Promise.each.hook (node_modules/sequelize/lib/hooks.js:126:19)
  From previous event:
      at Function.runHooks (node_modules/sequelize/lib/hooks.js:120:20)
      at Promise.map.instance (node_modules/sequelize/lib/model.js:2982:25)
  From previous event:
      at findAll.then._instances (node_modules/sequelize/lib/model.js:2971:26)
  From previous event:
      at Promise.try.then.then (node_modules/sequelize/lib/model.js:2960:12)
  From previous event:
      at Function.update (node_modules/sequelize/lib/model.js:2949:8)
      at Context.<anonymous> (test/all.test.js:451:23)
```

**Comment by overlookmotel** [comment]
And again on Travis with MySQL and Sequelize 2.1.3 on Node 10:

```
[MYSQL] Tests
       Methods
         #bulkUpdate
           "before each" hook for "sets hierarchyLevel for all rows":

SequelizeDatabaseError: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
      at Query.module.exports.Query.formatError (node_modules/sequelize/lib/dialects/mysql/query.js:157:16)
      at Query.<anonymous> (node_modules/sequelize/lib/dialects/mysql/query.js:35:23)
      at Query.<anonymous> (node_modules/mysql/lib/Connection.js:525:10)
      at Query._callback (node_modules/mysql/lib/Connection.js:491:16)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:91:28)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:525:10)
      at addChunk (_stream_readable.js:284:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at Socket.Readable.push (_stream_readable.js:220:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  From previous event:
      at Query.module.exports.Query.run (node_modules/sequelize/lib/dialects/mysql/query.js:30:19)
      at /home/travis/build/overlookmotel/sequelize-hierarchy/node_modules/sequelize/lib/sequelize.js:744:20
  From previous event:
      at Promise._then (node_modules/sequelize/lib/promise.js:14:16)
      at Model.beforeUpdate (lib/hooksModel.js:127:6)
      at /home/travis/build/overlookmotel/sequelize-hierarchy/node_modules/sequelize/lib/hooks.js:129:19
  From previous event:
      at Model.runHooks (node_modules/sequelize/lib/hooks.js:120:27)
      at /home/travis/build/overlookmotel/sequelize-hierarchy/node_modules/sequelize/lib/model.js:1692:25
  From previous event:
      at Model.<anonymous> (node_modules/sequelize/lib/model.js:1687:26)
  From previous event:
      at Promise._then (node_modules/sequelize/lib/promise.js:14:16)
      at Model.module.exports.Model.update (node_modules/sequelize/lib/model.js:1671:8)
      at Context.<anonymous> (test/all.test.js:451:23)
```

**Comment by overlookmotel** [comment]
I am hoping https://github.com/overlookmotel/sequelize-hierarchy/commit/fb2b47b2776d2cb4b0d8f5b28cf32959a572833e fixes this.
