### ISSUE TITLE
Folder.isHierarchy() faild to init

### ISSUE THREAD

**Issue by nengine** [overlookmotel/sequelize-hierarchy#163]
package.json
```js
    "pg": "^7.10.0",
    "sequelize": "^5.4.0",
    "sequelize-hierarchy": "^2.0.1",
```

pg_driver.js
```js
const Sequelize = require('sequelize-hierarchy')();
const config = require('../config');
const logger = require('../logger')

var pg = new Sequelize('pgdb', 'admin', 'password', {
  dialect: 'postgres',
  host: 'pg-01.mydomain.com'

})

module.exports = {
  pg,
  DataTypes: Sequelize,
  Model: Sequelize.Model,
  Op: Sequelize.Op
};
```

folder.js
```js
var { pg, DataTypes, Model } = require('./pg_driver');
class Folder extends Model {}
Folder.init({ 
    name: { type: DataTypes.STRING },
    parentId: {
        type: DataTypes.INTEGER,
        hierarchy: true
      }
 }, {    
    sequelize: pg
    })
module.exports = Folder;
```

app.js
```js

  await Folder.sync()
  await Folder.isHierarchy()

  var fa = await Folder.create({name: 'a'})
  var fab = await Folder.create({name: 'ab', parentId: 1})
  var fac =  await Folder.create({name: 'ac', parentId: 1})

  const folders = await Folder.findAll({ hierarchy: true });
  console.log(folders)
```

error
```txt
Executing (default): CREATE TABLE IF NOT EXISTS "Folders" ("id"   SERIAL , "name" VARCHAR(255), "parentId" INTEGER REFERENCES "Folders" ("id") ON DELETE RESTRICT ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "hierarchyLevel" INTEGER, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Folders' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
{ SequelizeAssociationError: You have used the alias children in two separate associations. Aliased associations must have unique aliases.
    at new Association (C:\Users\nash\workspace\nodeapps\oma-dpo\node_modules\sequelize\lib\associations\base.js:106:13)
    at new HasMany (C:\Users\nash\workspace\nodeapps\oma-dpo\node_modules\sequelize\lib\associations\has-many.js:19:5)
    at Function.hasMany (C:\Users\nash\workspace\nodeapps\oma-dpo\node_modules\sequelize\lib\associations\mixin.js:34:25)
    at Function.isHierarchy (C:\Users\nash\workspace\nodeapps\oma-dpo\node_modules\sequelize-hierarchy\lib\modelExtends.js:101:9)
    at Object.exports.Tree (C:\Users\nash\workspace\nodeapps\oma-dpo\seed\data.js:48:16) name: 'SequelizeAssociationError' }

```

**Comment by overlookmotel** [comment]
I think the problem is that you are essentially defining the hierarchy twice.

1. By adding `hierarchy` property on `parentId` field
2. By calling `Folder.isHierarchy()`

You should do only one or the other.

By the way:

* `Folder.isHierarchy()` is synchronous so doesn't require `await`
* `Folder.isHierarchy()` should be called *before* `Folder.sync()`
* You will also need to sync the `FolderAncestor` model which this library creates. `await pg.models.FolderAncestor.sync()` after `await Folder.sync()`

Please try that and let me know if it works. If not, please update sequelize and sequelize-hierarchy to latest versions and try that.

**Comment by nengine** [comment]
Hello, Thank you. It works now.  I do however need to rename FolderAncestor to Folderancestor. Otherwise got undefined errors.


```js
await pg.models.Folderancestor.sync()
```
