### ISSUE TITLE
Sequelize V6

### ISSUE THREAD

**Issue by lukichev** [overlookmotel/sequelize-hierarchy#174]
Should be pretty simple, the only breaking change I see is 'addHook'/'removeHook' removing. 
https://github.com/sequelize/sequelize/releases/tag/v6.0.0%40next

**Comment by overlookmotel** [comment]
Hi @lukichev. In theory yes! But it always seems to get more complicated than at first appears.

Want to do a PR?

(NB postgres-native on Node v10 is failing on Travis, for reasons that I think are to do with Travis config rather than the actual code, so you can ignore test fails on that one).

**Comment by bravo-kernel** [comment]
I will try to fix Travis, probably somewhere this weekend

**Comment by overlookmotel** [comment]
Thanks @bravo-kernel ! That'd be a big help. I copied the GCC config etc off Sequelize's Travis config, but that was probably a couple of years ago, and I guess it's out of date.

**Comment by bravo-kernel** [comment]
No problem, I have done quite a few Travis setups before so hopefully it 
will work out. I will at least give it a shot to make those merge 
buttons green again ;)

------ Original Message ------

**Comment by nicholasgriffintn** [comment]
The latest version, v6.2.3 results in the following error:

TypeError: Cannot read property 'coroutine' of undefined
    at makeCo (/node_modules/sequelize-hierarchy/lib/utils.js:103:31)
    at module.exports (/node_modules/sequelize-hierarchy/lib/modelExtends.js:21:17)
    at module.exports (/node_modules/sequelize-hierarchy/lib/index.js:28:23)
    at Object.<anonymous> (/src/database/models/index.js:9:31)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)

Figured I'd add this here as it seems related.

**Comment by lukichev** [comment]
@nicholasgriffintn , this is because Sequelize does not have Sequelize.Promise anymore and they're not using Bluebird now either. 
Current sequelize-hierarchy version is not suitable for Sequelize v6.

**Comment by juber-nunes** [comment]
Hey @lukichev. Any plans to have it working with Sequelize V6?

**Comment by jsanta** [comment]
Made a fork for this, planned to do a pull request but got stuck on other things...
https://github.com/jsanta/sequelize-hierarchy

**Comment by aaronovz1** [comment]
Looks like we both went down the same path to get a quick version working with V6. Looking to @overlookmotel to review whether this is acceptable to move forward with.

**Comment by rusekr** [comment]
Looking forward for this patch

**Comment by Capati** [comment]
Any updates?

**Comment by sciencebook** [comment]
I tried out @aaronovz1  's changes (Postgres dialect), did light testing and couldn't produce any errors.  I'm concerned about the "addHook"  here: https://github.com/overlookmotel/sequelize-hierarchy/blob/master/lib/modelExtends.js#L192 as that syntax is deprecated in Sequelize 6.

**Comment by lukichev** [comment]
@juber-ivre, I'm not a maintainer of this package, so I can't answer your questions. In our project, we were forced to drop sequelize-hierarchy package because there were no updates. 
So we're not using it anymore.

**Comment by nicholasgriffintn** [comment]
> @juber-ivre, we were forced to drop sequelize-hierarchy package because there were no updates.

What did you replace it with out of interest? Just some custom code? Or did you just remove it

**Comment by lukichev** [comment]
@nicholasgriffintn our own custom solution.

**Comment by nicholasgriffintn** [comment]
@lukichev Awesome, will probably do the same myself or fork this and see if I can get it working at some point, the usual lack of time though lol

**Comment by nicholasgriffintn** [comment]
For anyone still wondering, I made a private repo for this as this doesn't seem to be maintained and then I published it to our private registry on Github with the 2 pull requests:

https://github.com/overlookmotel/sequelize-hierarchy/pull/223

https://github.com/overlookmotel/sequelize-hierarchy/pull/178

I will be testing on my software over the next couple of days to see if there are any issues, but so far these changes look good.
